.travis.yml, package-lock.json, package.json, src/analytics.js, src/index.jsx
Call encapsulated Segment call to identify user for analytics.
ARCH-379
=> ARCH-379: Call identify user for analytics.

src/sagas/RootSaga.js
Update socialLinks in PROP_TO_STATE_MAP to provide proper format for saving.
=> Fix saving of Social Links

src/actions/AsyncActionType.js, src/actions/AsyncActionType.test.js, src/actions/profile.test.js, src/data/store.js, src/sagas/RootSaga.js, src/sagas/RootSaga.test.js
Also changing the way the saga gets ahold of the UserAccountApiService to make it more testable.
=> Tests for the saga, AsyncActionType, and profile actions.

package-lock.json, src/App.scss, src/components/UserProfile/MyCertificates.jsx, src/components/UserProfile/index.jsx, src/containers/UserProfile/index.jsx, src/sagas/RootSaga.js, src/services/ProfileApiService.js
Get certificates loaded in the UI.
Fakes the API call.
=> Add certificates

src/components/UserProfile/SocialLinks.jsx
Just playing around at the end of the day with restructuring the SocialLinks component per David's feedback.
=> Cleaning social links

src/components/UserProfile/elements/EmptyContent.jsx
=> Update empty states to match UX recommendation

src/index.scss, src/sagas/RootSaga.js
- There was an error caused by incorrectly fetching profile data after a successful upload preventing the UI from updating. 
- The profile photo no longer squishes horizontally on mobile
=> Photo uploading fixed

src/config/configureStore.dev.js
=> Collapse redux log groups in the console

src/components/NotFoundPage.jsx, src/components/ProfilePage/AgeMessage.jsx, src/components/ProfilePage/Bio.jsx, src/components/ProfilePage/Bio.messages.jsx, src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Certificates.messages.jsx, src/components/ProfilePage/Country.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Education.messages.jsx, src/components/ProfilePage/Name.jsx, src/components/ProfilePage/Name.messages.jsx, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/SocialLinks.messages.jsx, src/components/ProfilePage/elements/EditButton.jsx, src/components/ProfilePage/elements/EditButton.messages.jsx, src/components/ProfilePage/elements/FormControls.jsx, src/components/ProfilePage/elements/FormControls.messages.jsx, src/i18n/messages/es.json
This should be it for the hard-coded strings.
To be done in a followup:
* Country names
* Error strings
=> i18n all the things

src/components/ProfilePage.jsx, src/components/ProfilePage/DateJoined.jsx
https://openedx.atlassian.net/browse/ARCH-436
The year in "Member since 2017" is now dynamic.
=> Add "member since 2017"

.eslintignore, config/webpack.common.config.js, config/webpack.dev.config.js, src/analytics/analytics.js, src/analytics/segment.js, src/components/App.jsx, src/components/ProfilePage.jsx, src/components/ProfilePage.test.jsx, src/index.jsx
Moves analytics under its own folder under src.
=> Refactor analytics

src/components/ProfilePage/Certificates.jsx, src/config/environment.js, src/constants/certificates.js, src/selectors/ProfilePageSelector.js, src/services/ProfileApiService.js
This PR depends on https://github.com/edx/edx-platform/pull/19884 which adds a certificate list API endpoint on the backend.
=> fix(certificates): use real certificate data

src/actions/ProfileActions.js, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/elements/FormControls.jsx, src/components/ProfilePage/elements/FormControls.messages.jsx, src/sagas/RootSaga.js, src/services/ProfileApiService.js
- Save buttons never appear in a "save failed" state
- errors appear in the UI 
- Social Links errors appear at the top of the set of links (API needs update if we want per-field errors)
=> Better error handling

src/components/ProfilePage.jsx, src/components/ProfilePage/ProfileAvatar.jsx, src/selectors/ProfilePageSelector.js
Remove is no longer an option if the photo is the default
=> Handle default image better in ProfileAvatar

src/analytics/analytics.js, src/analytics/analytics.test.js
=> ARCH-492: Bug fix: JSON.stringify event data.

src/components/ProfilePage.jsx, src/components/ProfilePage/AgeMessage.jsx
- Also, remove the close button on the message
=> Do not show age message when viewing other's profiles

src/components/NotFoundPage.jsx
- Center text
- Uses inline styles
=> Style 404 Page

src/components/ProfilePage.jsx
This is a super-complicated PR.
=> Adding a horizontal rule below the joined date.

package-lock.json, package.json, src/analytics/analytics.js
Switch from custom function to form-urlencoded to perform form url
encoding.
ARCH-390
=> ARCH-390: Use form-urlencoded npm package.

src/components/ProfilePage.jsx, src/components/ProfilePage/PageLoading.jsx, src/components/ProfilePage/elements/Banner.jsx, src/index.scss, src/reducers/ProfilePageReducer.js, src/selectors/ProfilePageSelector.js
Adds a loading state. Loading is keyed off of the FETCH_PROFILE actions.
=> fix: add an app loading state

package-lock.json, src/components/ProfilePage.jsx, src/components/ProfilePage/Bio.jsx, src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Country.jsx, src/components/ProfilePage/Country.messages.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Name.jsx, src/components/ProfilePage/Name.messages.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/components/ProfilePage/PreferredLanguage.messages.jsx, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/elements/EmptyContent.jsx
- add help text to name field in editable or empty states
- change label of language to primary language spoken
- add labels to top of empty states
=> fix: ui polish

config/webpack.dev.config.js, config/webpack.prod.config.js, src/components/ProfilePage.jsx, src/components/ProfilePage.messages.jsx, src/config/environment.js
Links to credentials.edx.org/records
This PR should go in _after_ https://github.com/edx/edx-internal/pull/778 has been merged and deployed
=> Add a “View My Records” button.

src/components/ProfilePage.jsx, src/components/ProfilePage/Certificates.jsx, src/index.scss
Consistent height and watermark placement.  Also, no watermark by default.
=> Improve card styling.

src/selectors/ProfilePageSelector.js
This is the best place I could think of to put the note.
=> style: i18n comment

public/index.html
=> Update page title to match existing profile.

src/components/App.jsx, src/sagas/RootSaga.js, src/services/LoggingService.js, src/services/LoggingService.test.js, src/services/ProfileApiService.js
- Logs errors that fall through to the App.
- Logs unprocessed error in Saga.
- Ensures ProfileApiService throws proper errors.
- Fix LoggingService to pass through non-API errors.
- Fix LoggingService to cap length of message.
ARCH-427
FYI: @edx/arch-squad
=> ARCH-427: Fix and log more unhandled errors.

package-lock.json, package.json, src/services/LoggingService.js, src/services/LoggingService.test.js
- Add custom attributes to api response errors.
- Add custom attribute capabilities to loadError.
- Drop the data for html page responses.
- Move code for max message length.
- Add tests.
ARCH-578
FYI: @edx/arch-squad
=> ARCH-578: Enhance the logging service.

src/components/ProfilePage.jsx
See it in action here: https://profile.edxdev.org/u/verified
=> ARCH-584 Disable profile image editing for user's with no age or younger than 13.

src/components/ProfilePage/Certificates.jsx
Depends on https://github.com/edx/edx-platform/pull/20045.
See it in action at: https://profile.edxdev.org/u/verified
=> Display certificate issue date on certificate cards.

src/services/ProfileApiService.js
See it in action here: https://profile.edxdev.org/u/verified
=> ARCH-497 Prevent certificate list API call failure from crashing page.

src/actions/ProfileActions.js, src/actions/ProfileActions.test.js, src/components/App.jsx, src/components/ErrorPage.jsx, src/sagas/RootSaga.js
See it in action here by attempting to change profile data: https://profile.edxdev.org/u/verified
=> ARCH-566 Display error page when unexpected errors occur.

config/webpack.prod.config.js, package-lock.json, package.json, src/i18n/i18n-loader.js, src/index.jsx
See it in action here: https://profile.edxdev.org/u/verified
=> ARCH-560 Add RTL capabilities.

src/index.jsx
I have created https://openedx.atlassian.net/browse/ARCH-628 to address RTL in the dev environment.
=> Turn off RTL support for dev environment.

src/services/LoggingService.js
Trying to add some additional information to our error logging in hopes of better understanding the errors we are seeing in new relic.
=> Add additional data to error logging.

src/services/LoggingService.js
Another attempt to get more actionable data in new relic error logging.
=> ARCH-619 Add request URL to request error logging.

src/components/ProfilePage/Country.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/constants/countries.js, src/constants/languages.js, src/i18n/i18n-loader.js, src/selectors/ProfilePageSelector.js
And also sort them by their localized values.
=> Allow languages and countries to be localized.

src/analytics/analytics.js, src/analytics/analytics.test.js, src/analytics/segment.js, src/components/App.jsx, src/components/ProfilePage.jsx, src/components/ProfilePage.test.jsx, src/config/analytics.js, src/index.jsx
- Make analytics and segment files configurable from outside.
- Add checks for previously called identify on page/track.
- Add some additional parameters to tracking events.
ARCH-517
FYI: @nasthagiri
=> ARCH-517: prepare analytics for move to separate repo

src/components/ProfilePage/Certificates.jsx
=> Render certificates after the visibility editing form.

src/components/ProfilePage/Bio.jsx, src/components/ProfilePage/Country.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Name.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/elements/Banner.jsx, src/components/ProfilePage/elements/EditableItemHeader.jsx, src/components/ProfilePage/elements/EmptyContent.jsx, src/components/ProfilePage/elements/FormControls.jsx, src/components/__snapshots__/ProfilePage.test.jsx.snap, src/index.scss
Various design tweaks. [Source](https://openedx.atlassian.net/browse/ARCH-624).
- Remove underline from button links
- Underline should not disappear on hover on text links
- Edit and cancel buttons should be underlined
- Update the old blue to the new navy in the hero image
- More space between sections – use mb-5
- Label, edit button, and visibility should be inline in right, main column (About Me and Certificates sections)
- Empty state button's should use cursor:pointer on hover
- Empty state buttons are display:inline-block
- Make H2 and LABEL elements the same line-height so they don't appear to shift when opening a form field
=> Design updates

config/webpack.dev.config.js, config/webpack.prod.config.js, package-lock.json, package.json, src/config/environment.js, src/i18n/i18n-loader.js
Some notes:
- Adds a dependency `universal-cookie`.
- the cookie value is a two-letter language code
- Should not be merged until stage and prod configuration is updated
=> feat: lookup language preference in cookie

package-lock.json, package.json, src/index.jsx
Related PR:
https://github.com/edx/frontend-auth/pull/22
=> ARCH-653 Upgrade frontend-auth and conform to new signature of ensurePublicOrAuthenticationAndCookies

package-lock.json, package.json
Frontend-logging PR: https://github.com/edx/frontend-logging/pull/3
=> feat: upgrade frontend-logging to show errors and logs in dev console

src/profile/components/ProfilePage.jsx
Pass the correct properties, sir.
=> URL != Url

package-lock.json, package.json, webpack/webpack.prod.config.js
=> ARCH-587: upload source maps to newrelic

package-lock.json, package.json, src/profile/components/__snapshots__/ProfilePage.test.jsx.snap, src/profile/components/forms/Certificates.jsx, webpack/webpack.dev.config.js, webpack/webpack.prod.config.js
- Remove extra loader from webpack for svgs. Was svgr-loader, url-loader, and file-loader. Url-loader and file-loader together were creating problems.
- Add a better key for iterating over certificates. It was downloadURL and now it's the courseId + modifiedDate.
- Removed program certificates from the frontend code for now.
=> fix: loading of certificate images

package-lock.json, package.json, webpack/webpack.prod.config.js
=> add sourcemaps for dependencies

package-lock.json, package.json, src/i18n/injectIntlWithShim.jsx, src/index.jsx, src/profile/sagas.js, src/profile/services.js
- The logging service is now configured and used via an interface,
rather then from the concrete implementation.
- The logging service is passed to frontend-auth.
ARCH-687
=> ARCH-687: update frontend-logging and frontend-auth

package-lock.json, package.json
I thought this was pulled in in the last commit, but I made a mistake.
ARCH-687
=> update frontend-auth for real

package-lock.json, src/profile/components/__snapshots__/ProfilePage.test.jsx.snap, src/profile/components/forms/elements/FormControls.jsx
=> fix: remove use of margin auto for layout where it breaks in ie11

src/common/components/ReloadOnError.jsx, src/common/index.js, src/components/App.jsx, src/index.jsx
Steps to reproduce the bug:
1. Install Google Translate chrome extension.
2. Visit https://profile.edx.org/u/{your username}.
3. Open Google Translate Chrome extension.
4. Click “TRANSLATE THIS PAGE”.
5. Select “Chinese (Traditional)”.
6. Update the bio field and save.
7. BOOM!
=> Handle Google Translate DOM manipulation error scenario.

package-lock.json, package.json, src/index.jsx
- Since we are tracking down a flaky issue, the sooner we can get this out the better.
- Although we are looking into problem for the new Payment MFE, the Profile MFE currently gets the most traffic, so adding this here.
Looking into an issue where the auth state might not match.  This is
a temporary change that should ultimately be reverted once the issue
is fully involved.
This includes an upgrade to @edx/frontend-logging which does not need
to be reverted.
ARCH-982
=> ARCH-982: temporary addition of debugging info for auth state

package.json, webpack.prod.config.js
Reverts edx/frontend-app-profile#326
=> Revert "build: add newrelic plugin back in as experiment"

src/profile/ProfilePage.jsx, src/profile/ProfilePage.test.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap
This hides the "View My Records" button from users profile page if `CREDENTIALS_BASE_URL` is not configured.
**Sandbox**: https://mfeplayground-master.opencraft.hosting/
=> Hide 'View My Records' button if no credentials service.

Makefile, package-lock.json, package.json, src/profile/AgeMessage.jsx
[migrate reactifex in CE MFE repos](https://openedx.atlassian.net/browse/PROD-2743)
=> feat: migrate translations to reactifex

.github/workflows/ci.yml, Makefile, package-lock.json, package.json, src/profile/__snapshots__/ProfilePage.test.jsx.snap
Updated frontend-platform version with GA4 implementation.
[FC-0014 - Google Analytics 4 Upgrade](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3668312128/FC-0014+-+Google+Analytics+4+Upgrade)
=> [FC-0014][olive] update frontend-platform version to v4.2.0

src/skills-builder/skills-builder-modal/SkillsBuilderModal.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestCard.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/GoalSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/test/SelectPreferences.test.jsx, src/skills-builder/skills-builder-modal/view-results/CarouselStack.jsx, src/skills-builder/skills-builder-modal/view-results/RecommendationCard.jsx, src/skills-builder/skills-builder-modal/view-results/ViewResults.jsx, src/skills-builder/skills-builder-modal/view-results/test/ViewResults.test.jsx, src/skills-builder/test/__mocks__/jobSkills.mockData.js
This adds analytics events to track a user's progress through the Skills Builder. These events are outlined in more detail on the [Events to monitor KPIs for Skills Builder](https://2u-internal.atlassian.net/wiki/spaces/microb/pages/395477339/Eventing+to+monitor+KPIs+for+Skills+Builder) page.
Several event handle functions have been modified/created and tests written to check their behavior.
=> APER-2333: Dispatch segment events from JS components

src/skills-builder/skills-builder-modal/view-results/CarouselStack.jsx, src/skills-builder/skills-builder-modal/view-results/ViewResults.jsx, src/skills-builder/skills-builder-modal/view-results/test/ViewResults.test.jsx
We noticed that two of our events were not firing when we expected them to:
- `edx.skills_builder.recommendation.shown`
- `edx.skills_builder.recommendation.click`
After checking the [Segment documentation](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/troubleshooting/#is-there-a-size-limit-on-requests), we learned that there is indeed a limit put on the payload for the event.
Check the [wiki page for more details](https://2u-internal.atlassian.net/wiki/spaces/ENGAGE/pages/445612347/Segment+dropping+events+with+large+payload).
This PR modifies the payload of these two events so that they don't include nearly as much data. Previously, we were nesting the entire Algolia response into the payload. We did this so that we have a reference to each …
=> fix: reduce event payload

renovate.json
[Create common renovate config that automates @edx and @openedx namespaced minor/patch version upgrades](https://github.com/openedx/wg-frontend/issues/116#event-10495007446)
Add `@openedx` in renovate automate configuration.
=> refactor: add openedx in renovate automate configuration

package-lock.json, package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
=> chore: bump frontend-platform (#869)

src/profile/ProfilePage.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap
=> feat: add little tag to identify POC

src/index.jsx, src/profile/ProfilePluginPage.jsx
This PR will add the user's full name to the Profile Plugin page, as well as fix the hyperlink in the plugin to send the user to their Profile page.
=> fix: hyperlink in plugin page should redirect to user profile

.github/CODEOWNERS
this is a dependency for other parts of the flow
FIXES: APER-3263
=> feat:  adding codeowners

.github/CODEOWNERS
I used internal team name, fixing to external
FIXES: APER-3263
=> feat: fixing codeowners

package-lock.json, package.json
rebase 2u-main branch with master branch
=> chore: rebase 2u-main with master

package.json
Reverts openedx/frontend-app-profile#1104
=> Revert "chore(deps): update dependency @testing-library/react to v16"

package-lock.json, package.json
=> Rebase 2u-main

package-lock.json, src/profile/__snapshots__/ProfilePage.test.jsx.snap
- The updated profile test that was failing can be found in the package update pull request linked [here](https://github.com/openedx/frontend-app-profile/pull/1175).
=> test: updated profile test cases

package-lock.json, package.json, src/index.jsx, src/plugin-slots/FooterSlot/README.md, src/plugin-slots/README.md
https://app.pr-1198-2dd30d.sandboxes.opencraft.hosting/profile/u/openedx
=> feat: import `FooterSlot` from component package instead of slot package

src/index.jsx
Added the `DISABLE_VISIBILITY_EDITING` flag to the index file.
=> fix: added DISABLE_VISIBILITY_EDITING flag to index

src/profile/data/actions.js
Ticket: [INF-2009](https://2u-internal.atlassian.net/browse/INF-2009)
Fixed a bug in the country list not showing in the dropdown. Added country code list to profilePage state.
=> fix: added country code list to profilePage state

src/profile/data/sagas.test.js, src/profile/data/services.test.js, src/profile/forms/elements/FormControls.test.jsx, src/profile/forms/elements/SwitchContent.test.jsx
[INF-2057](https://2u-internal.atlassian.net/browse/INF-2057)
Improve Profile MFE Test coverage to 75%
=> test: added test cases to improve test coverage
