openedx/frontend-app-profile

package-lock.json, package.json, src/analytics.js, src/index.jsx
ARCH-378: Fire segment event for footer through app.
FYI: Uses updated footer from this PR: https://github.com/edx/frontend-component-footer/pull/5
=> ARCH-378: Add event tracking from footer.

config/webpack.common.config.js, config/webpack.dev.config.js, config/webpack.prod.config.js, src/actions/profile.js, src/actions/profile.test.js, src/components/NotFoundPage.jsx, src/components/UserProfile/index.jsx, src/containers/UserProfile/index.jsx, src/data/reducers/ProfilePageReducer.js, src/data/reducers/RootReducer.js, src/data/store.js, src/index.jsx, src/sagas/RootSaga.js, src/sagas/RootSaga.test.js, src/services/ProfileApiService.js, src/services/ProfileApiService.test.js
This PR allows users to view other user's profiles.  It also changes the path of our app to `/u/<username>`.  If you go to just `/` you'll get a simple 404 page.
This PR also has a refactoring of our actions/sagas/services.  Rather than continue to put profile-related API actions into the frontend-auth project, we decided (against prior decision) to put them in this app, as that feels more correct long term than overloading the API service in frontend-auth with things that aren't specific to auth.  This also let us unroll the service creation and decouple the services from the components (compare the way fetchUserAccount is called in the index.jsx file with the way the ProfileApiService can be called in the sagas).
Note that the “fetchProfile” API is hitting the same ‘accounts’ API as …
=> Viewing others profiles and naming refactor.

src/components/UserProfile/elements/EmptyContent.jsx, src/components/UserProfile/elements/TransitionReplace.jsx, src/components/UserProfile/index.jsx, src/containers/UserProfile/index.jsx
If a field isn’t present in another users profile (they either haven’t set it, or it’s not publicly visible), then hide it completely.  If the field is present, then show it in a static way.
The change to EmptyContent was because I kept getting a warning from it, and I think `node` is more accurate to what we expect there.  Similarly, I modified TransitionReplace so that it could render "nothing at all" if desired.  This is used for hidden fields as described above.
=> Properly display fields on other users profiles.

src/components/UserProfile/elements/TransitionReplace.jsx
Since we've added the ability for transition replace to have no content, we can't guarantee an onChildExited event will fire resetting the hieght to null
=> TransitionReplace Improvement

src/components/ProfilePage.jsx, src/components/ProfilePage/AgeMessage.jsx, src/index.scss, src/sagas/RootSaga.js
Looks only at the `requiresParentalConsent` boolean. It seems that this is false when `yearOfBirth` is null or less than 13 years ago. It's worth noting that this differs from the [current logic on the profile page](https://github.com/edx/edx-platform/blob/1a8df4517943a15b2d1c71be8ea44c4f6382d00c/lms/static/js/student_account/models/user_account_model.js#L58) seen here:
```
isAboveMinimumAge: function() {
var yearOfBirth = this.get('year_of_birth');
var isBirthDefined = !(_.isUndefined(yearOfBirth) || _.isNull(yearOfBirth));
return isBirthDefined && !(this.get('requires_parental_consent'));
}
```
=> Add age messaging

src/services/ProfileApiService.js
`yearOfBirth` and `requiresParentalConsent` were missing from redux state. This adds them to the clientServer key map in ProfileAPIService.
=> Fix age messaging

package-lock.json, package.json, src/components/ProfilePage.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/components/ProfilePage/elements/EditableItemHeader.jsx, src/constants/languages.js
It only displays and saves one – parity with the profile page today.
The API is prepared to handle an array of languages when we're ready
=> Add language proficiency field

src/components/ProfilePage.jsx, src/components/ProfilePage.test.jsx
Had temporarily named the event edx.bi.profile.viewed while working
out some details. Now that the backend will add user_id for the
username, the event can become more official.
ARCH-491
=> ARCH-491: Rename event to edx.profile.viewed.

src/services/ProfileApiService.js
The certificates API can return both absolute and relative download URLs depending on whether or not the certificate is PDF or web.
=> fix(certificates): handle absolute and relative certificate download urls

src/selectors/ProfilePageSelector.js
If a user has never set their account privacy, it defaults to "all_users" - crazy as that sounds.
Therefore, if we don't receive an account_privacy in the preferences, we should reflect that and default to all_users.
=> If account_privacy is blank, that means “all_users”

src/analytics/analytics.js, src/analytics/analytics.test.js
The LMS /event api expects the request to use a content type of
application/x-www-form-urlencoded.
ARCH-390
FYI: @edx/arch-squad
=> ARCH-390: Fix analytics events to be x-www-form-urlencoded.

src/components/ProfilePage/ProfileAvatar.jsx, src/reducers/ProfilePageReducer.js
Also removes flipping the isLoadingProfile state when fetching a profile begins.
Desired behavior: Any time a whole profile is being loaded show the loading state. 
Right now the upload photo endpoint doesn't return the url we need so we refetch the whole profile again. This causes the whole page to appear to reload.
For now removing the resetting of isLoadingProfile to true inside FETCH_PROFILE.BEGIN will mean that isLoadingProfile is only true when the app first loads (it is the default state). We can uncomment this line in the future when we update the upload profile endpoint.
=> fix: remove the upload button background when viewing other profiles

src/components/ProfilePage/Name.jsx, src/components/ProfilePage/elements/Visibility.jsx
As per @nasthagiri, shutting off name editing.
Also fixing a layout ugliness I noticed in the visibility.  The eyeball icon was a little too cozy with the text label.
=> Shut off name editing and tweak visibility spacing

src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Certificates.messages.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Education.messages.jsx, src/constants/certificates.js, src/constants/education.js, src/services/ProfileApiService.js
1. Internationalizes the certificate and education types.
2. Moves the localization of certificates into the Certificates.jsx component, rather than in the API.  (Keep it as a code until the last second)
=> Internationalize the certificate and education types.

package-lock.json, package.json, src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Education.jsx
intl.formatMessage will error out if it's provided a message id that doesn't exist. This PR adds default ids to certificate and education level strings.
=> fix: use lodash.get to provide default message ids to intl.formatMessage

.eslintrc, package-lock.json, package.json, src/components/ErrorPage.jsx, src/components/NotFoundPage.jsx, src/components/ProfilePage.jsx, src/components/ProfilePage/AgeMessage.jsx, src/components/ProfilePage/Bio.jsx, src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Country.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Name.jsx, src/components/ProfilePage/PageLoading.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/components/ProfilePage/ProfileAvatar.jsx, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/elements/AsyncActionButton.jsx, src/components/ProfilePage/elements/FormControls.jsx, src/components/ProfilePage/elements/Visibility.jsx, src/components/__snapshots__/ProfilePage.test.jsx.snap, src/index.scss
This PR shows what it would look like to use raw html for form elements instead of Reactstrap. Using this as an experiment to determine if we should bring Reactstrap form components into Paragon.
My take: I think we should not include Reactstrap. HTML alleviates the need for another dependency, keeps developers closer to the html (I think a good thing), and gets the job done despite some extra bloat from bootstrap class names. Paragon should add documentation for these class names to prevent developers from bouncing back and forth between bootstrap and paragon docs.
Instead of building input, textarea, select, etc as React components I think we should rely on linters for a11y enforcement and React container components like a [Form Group (example …
=> Use raw html form elements

config/webpack.common.config.js, config/webpack.dev.config.js, src/analytics/analytics.js, src/analytics/analytics.test.js, src/analytics/segment.js, src/components/App.jsx, src/components/ProfilePage.jsx, src/components/ProfilePage.test.jsx, src/config/analytics.js, src/index.jsx
- Make analytics and segment files configurable from outside.
- Add checks for previously called identify on page/track.
- Add some additional parameters to tracking events.
- Note: fixes some loading/import issues from 'take 1'
ARCH-517
As noted in the commit comment, this PR is largely the same as https://github.com/edx/frontend-app-profile/pull/135, but fixes some loading issues I can point out with comment.
=> ARCH-517: prepare analytics for move to separate repo (take 2)

package-lock.json, package.json
The update to NewRelic snippet was merged upstream, so we can now use
the upstream version again.
=> drop fork of html-webpack-new-relic-plugin

src/components/ProfilePage/elements/FormControls.jsx, src/components/ProfilePage/elements/SwitchContent.jsx, src/components/__snapshots__/ProfilePage.test.jsx.snap
Opening and closing a form now redirects focus only if its child currently has the active (focused) element.
This change prevents focus issues when opening a form while another is already open where you could not guarantee focus would be in the desired place (the first element of the new content the user has opened).
=> fix: handle focus control better for opening and closing forms.

src/sagas/RootSaga.js, src/sagas/RootSaga.test.js, src/selectors/ProfilePageSelector.js
We can’t use isAuthenticatedUserProfileSelector before we’ve actually loaded the profile - the username will be null.  Instead, we want to compare the username of the profile we’re supposed to load with the username in the authentication part of the store.
=> Compare the right usernames.

package-lock.json, package.json, src/components/App.jsx, src/sagas/RootSaga.js, src/sagas/RootSaga.test.js
If the fetchUserAccount action results in a failure of some sort, redirect to the error page.  
This PR relied on exporting the fetch user account action types from frontend-auth, thus the bump there.
=> Redirect to error page on fetch user account failure

src/i18n/i18n-loader.js
Can now handle values like `es-415` in the cookie
=> fix: get two letter language code from cookie

src/i18n/i18n-loader.js
There was a mistake in the prior fix. The language was being trimmed after checking to see if it was a supported language. Now it gets the two letter language code before doing that check.
=> fix: locale loading user setting

package-lock.json, src/actions/ProfileActions.js, src/actions/ProfileActions.test.js, src/reducers/ProfilePageReducer.js, src/sagas/RootSaga.js, src/services/ProfileApiService.js
Fixes bug: Uploaded photos on the profile page do successfully upload and update, but changes are not reflected until refreshing the page.
To reduce api calls we removed the refetching of user profile data. This is fine for other fields because they receive the newly set values from the server in their post/patch requests. The photo upload doesn't do this and needs to refetch the profile data. This was done by firing the fetchProfile action (which now doesn't refetch the user's data). 
To solve this the API service functions `postProfilePhoto` and `deleteProfilePhoto` now call `getAccount` directly. They now return the new/updated photo data themselves. This matches what should happen in the future when the POST profile endpoint returns updated values on success.
=> fix: get profile photo changes from calls back into redux store

config/webpack.common.config.js, package-lock.json, package.json, src/components/App.jsx, src/components/ProfilePage.jsx, src/components/ProfilePage/Bio.jsx, src/components/ProfilePage/Certificates.jsx, src/components/ProfilePage/Country.jsx, src/components/ProfilePage/Education.jsx, src/components/ProfilePage/Name.jsx, src/components/ProfilePage/PreferredLanguage.jsx, src/components/ProfilePage/ProfileAvatar.jsx, src/components/ProfilePage/SocialLinks.jsx, src/components/ProfilePage/elements/EditButton.jsx, src/components/ProfilePage/elements/FormControls.jsx, src/components/ProfilePage/elements/Visibility.jsx, src/components/common/SiteHeader.jsx, src/i18n/index.jsx, src/i18n/injectIntlWithShim.jsx, src/selectors/ProfilePageSelector.js
- Adds a shim replacement for injectIntl to override intl.formatMessage so it won't blow up when supplied an undefined message definition.
- Adds an index.js file to the i18n folder to start prepping it to be pulled out into a package
- Added an alias for @edx/frontend-i18n in the webpack config and jest config (package.json) to allow the rest of the code be written as if this package already existed.
=> fix: make intl.formatMessage more resilient

package-lock.json, src/profile/services.js
Our usage of `new URL()` to parse certificate download URLs causes errors in IE 11 where it is unsupported. This refactors the construction of the download URL, which is supplied either as a path or a full URL.
=> fix: remove use of URL which is unsupported in IE 11

src/profile/sagas.js, src/profile/sagas.test.js
Wait for 1000ms instead of 300ms after successfully saving before closing a form
=> fix: delay closing a form on success so a user can read the message

package-lock.json, package.json, src/profile/sagas.js, src/profile/sagas.test.js
Fixes: https://openedx.atlassian.net/browse/ARCH-687
Users who trigger an API request after being logging out in a separate tab or waiting until after their session expires will continue to be redirected to login, but we will not log an error to NewRelic.
Note: This will not eliminate this error in our logs entirely. We will continue to log this error for an API response of 401 or 403, just not if that request was directed to login_refresh.
=> fix: upgrade frontend auth

Makefile
ARCH-7481
update i18n make targets
* update extract_translations to also concat
* update push_translations to push to Transifex
* remove call to i18n.extract as part of push_translations
@albemarle: This PR adds `i18n.concat` to the `extract_translations` that the Jenkins scripts [push script](https://github.com/edx/ecommerce-scripts/blob/master/transifex/push.py#L3-L4) relies on.
I think this solves part of the problem, but having `extract_translations` do everything needed to prep source files to be committed.
Next, I plan to also add a separate script and job (called `update_sources`) to only call `extract_translations`, that can be called daily.
Let me know what you think of this PR and this plan.
=> ARCH-748: update i18n make targets

package-lock.json, package.json, webpack/webpack.prod.config.js
Purged CSS shrinks from 253kb for each ltr and rtl css files down to 27kb. 
Important Note: PurgeCSS will remove CSS the app actually needs if we aren't careful. This could result in a hard to identify problem in the future if a non-edX React component that has styles is used in the app. It will appear fine in development but the CSS will be stripped out in production. To fix, the package directory would need to be added to the PurgeCSS configuration.
=> feat: remove unused CSS with purgecss

README.rst, webpack/webpack.prod.config.js
Increases the size of CSS files from 27kb to 45kb each, but now includes all styles for Paragon components.
=> fix: add paragon files to purgecss scan

package-lock.json, package.json, src/index.jsx, src/postcss.config.js, webpack/webpack.dev.config.js, webpack/webpack.prod.config.js
In order to work, this PR will need to upgrade to a version of frontend-i18n that sets the dir attribute on the html to ltr or rtl in all cases and does not attempt to handle stylesheet toggling.
See: https://github.com/edx/frontend-i18n/pull/12
=> feat: use postcss to handle rtl

src/profile/components/forms/Country.jsx, src/profile/components/forms/Education.jsx, src/profile/components/forms/PreferredLanguage.jsx
ARCH-1165: Add an empty option so that users can delete values they set for education, spoken language, and country of origin
=> fix: add empty options to dropdowns

package-lock.json, package.json, src/index.jsx
frontend-base 2.1.x had a bug where segment wasn’t being initialized.  Now it is.
Also allowing frontend-base to use its default logging service, which is NewRelicLoggingService.
=> fix: bump frontend-base to 2.2.0 to initialize segment

package-lock.json, package.json
frontend-base wasn’t calling identifyAuthenticatedUser and sendPageEvent.  Version 4.1.0 does.
=> fix: send analytics events

src/profile/ProfilePage.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/forms/Bio.jsx, src/profile/forms/Country.jsx, src/profile/forms/Education.jsx, src/profile/forms/Name.jsx, src/profile/forms/PreferredLanguage.jsx, src/profile/forms/ProfileAvatar.jsx
Hotjar is a behavior analytics tool that analyses website use, providing feedback through tools such as heatmaps, session recordings, and surveys. Before we enable hotjar we have to suppress all PII and sensitive information so that screen recorder doesn’t capture it. Adding a `data-hj-suppress` attribute around the sensitive data marks the field as suppressed for hotjar and shows asterisks instead of text.
For Profile MFE, PII identified and suppressed are:
- Profile Avatar
- Name
- Location
- Preferred Language
- Bio
- Education
- Username on profile
- Username in header suppressed in edx/frontend-component-header-edx#98 (PR to bump the version for profile MFE: https://github.com/edx/edx-internal/pull/3210)
Ticket: [VAN-35](https://openedx.atlassian.net/browse/VAN-35)
=> feat: add hotjar suppression to PII

.gitignore
module.config.js is a file manually created by developers in their environment that allows them to link local libraries into their build.  It should never be committed.
=> build: add module.config.js to .gitignore

renovate.json
We've adopted a looser renovate config that will auto-merge more things in other repositories, and it's worked out fine.  I just lifted this config from frontend-platform, which was itself based on prospectus (private).
=> chore: let renovate be more liberal about what it merges

package-lock.json, package.json
This PR installs `@edx/frontend-build` from a Git branch. This particular checkout of `@edx/frontend-build` uses a forked `new-relic-source-map-webpack-plugin` that should be compatible with Webpack 5.
Forked plugin repo: https://github.com/edx/new-relic-source-map-webpack-plugin
`@edx/frontend-build` updates: https://github.com/edx/frontend-build/pull/195
This PR serves as a trial to see whether source maps will be uploaded to New Relic as expected to help parse JS error instances.
=> build: test new relic source maps with webpack 5

src/i18n/messages/ar.json, src/i18n/messages/es_419.json, src/i18n/messages/fr.json, src/i18n/messages/zh_CN.json, src/profile/AgeMessage.jsx, src/profile/UsernameDescription.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/forms/elements/Visibility.jsx, src/profile/forms/elements/Visibility.messages.jsx
Description
This PR backports (cherry picked from commit https://github.com/openedx/frontend-app-profile/commit/1acc1d026212155338bcd4ad4322336d5e323c1c) changing references from edX to the proper site name. Refer to https://github.com/openedx/build-test-release-wg/issues/156 for more information about the backport.
=> fix: show site name instead edX

src/profile/ProfilePage.test.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/forms/Bio.jsx, src/profile/forms/Country.jsx, src/profile/forms/Education.jsx, src/profile/forms/PreferredLanguage.jsx
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102#)
Updated deprecated `ValidationFormGroup` to `Form.Group`, `Input` to `Form.Control` and `Checkbox` to `Form. CheckBox`.
Tested on edx.org theme.
=> Paragon form component deprecations

.github/workflows/ci.yml, Makefile, package-lock.json, package.json, src/profile/__snapshots__/ProfilePage.test.jsx.snap
* Removes custom `browserslist` configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
* Removes `is-es5` check in CI since ES5 was only needed for IE 11 support which is dropped. The supported browsers defined by the shared configuration all [natively support ES6](https://caniuse.com/?search=es6).
This change reduces the resultant asset bundle size.
* Update `edx/paragon` version
=> build: use shared browserslist configuration and upgrade paragon version

src/skills-builder/data/actions.js, src/skills-builder/data/constants.js, src/skills-builder/data/reducer.js, src/skills-builder/data/test/reducer.test.js, src/skills-builder/skills-builder-modal/SelectPreferences.jsx, src/skills-builder/skills-builder-modal/SkillsBuilderModal.jsx, src/skills-builder/skills-builder-modal/ViewResults.jsx, src/skills-builder/skills-builder-modal/messages.js
This adds more actions to the `SkillsBuilderContext` and shows a simple demonstration for how they will be implemented when building out the UI.
In addition, some of the components have been set up for future development  — `<SelectPreferences>` and `<ViewResults>` each represent one step of the Skills Builder (`<Stepper>` component).
The `useHistory` hook from `react-router` is now utilized by the `onClose` prop for the Modal — in place of using the [Window interface](https://developer.mozilla.org/en-US/docs/Web/API/Window).
[APER-2185: Define the rest of actions and reducer for Skills Builder](https://2u-internal.atlassian.net/browse/APER-2185)
https://user-images.githubusercontent.com/92897870/217348633-933963b8-c46a-4191-9752-452db4f95b45.mov
=> feat: adding actions and reducer for Skills Builder

src/skills-builder/utils/search.jsx, src/skills-builder/utils/tests/search.test.jsx
[APER-2262]
- add a utility function to retrieve product recommendations based on skills from a job a learner is interested in
- add additional tests and coverage around new utility functions in `search.jsx`
=> feat: add utility function to retrieve product recommendations based on job skills

README.rst
The @edx/arch-fed group no longer exists - this repo is maintained by the @openedx/2u-aperture team.
fixes #694
=> docs: update the maintaining group to openedx/2u-aperture

src/skills-builder/data/actions.js, src/skills-builder/data/constants.js, src/skills-builder/data/reducer.js, src/skills-builder/data/test/reducer.test.js, src/skills-builder/skills-builder-modal/SkillsBuilderModal.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestCard.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/GoalSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleInstantSearch.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/SelectPreferences.jsx, src/skills-builder/skills-builder-modal/select-preferences/messages.js, src/skills-builder/test/SkillsBuilder.test.jsx
This PR adds a selection component that enables the user to select potential career interests from a list of job titles. The `JobTitleInstantSearch` component was able to be reused here.
In addition to writing tests for new components, some other tests in the `SkillsBuilder.test.jsx` suite were modified to be a little more robust. 💪  There was also a spelling typo for the `REMOVE_CAREER_INTEREST` action that was fixed.
There is one custom component here: the `CareerInterestCard`. It is a simple card that employs utility classes from Paragon and will dismiss itself when it's corresponding close button is selected.
=> feat: SkillsBuilder career interests selection

src/skills-builder/skills-builder-modal/SkillsBuilderModal.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestCard.jsx, src/skills-builder/skills-builder-modal/select-preferences/CareerInterestSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/GoalSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleInstantSearch.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/SelectPreferences.jsx, src/skills-builder/skills-builder-modal/select-preferences/messages.js, src/skills-builder/skills-builder-modal/view-results/RelatedSkillsSelectableBoxSet.jsx, src/skills-builder/skills-builder-modal/view-results/ViewResults.jsx, src/skills-builder/skills-builder-modal/view-results/messages.js, src/skills-builder/test/SkillsBuilder.test.jsx, src/skills-builder/test/__mocks__/jobSkills.mockData.js
This PR adds a set of `SelectableBox` components to Step 2 of the `SkillsBuilder`. Each box contains a job title with related skills. To retrieve the related skills, the learner's `careerInterests` are passed to Algolia using a utility function. The skills are then used to retrieve course recommendations using another Algolia utility function.
[APER-2187](https://2u-internal.atlassian.net/browse/APER-2187) — Render jobs and related skills
=> APER-2187 Render jobs and related skills for Skills Builder

.env.test, package-lock.json, package.json, src/index.jsx, src/routes/AppRoutes.jsx, src/routes/routes.test.jsx
This PR will allow unauthenticated users access to certain routes on the Profile MFE. Currently this will be needed for the B2C Skills Builder that will be released soon. The `hydrateAuthenticatedUser` flag is still set to `true` and we will still have access to the extra data that it provides so long as the user is logged in.
The routes have been refactored into their own component (`AppRoutes`) so they can be easily tested. These tests will help ensure that the `ProfilePage` route remains protected. In order to test components from `react-router`, we needed to import the `history` package. Tests have also been written for the other routes on this MFE.
=> fix: authenticated page route

src/skills-builder/skills-builder-modal/select-preferences/CareerInterestSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/JobTitleSelect.jsx, src/skills-builder/test/setupSkillsBuilder.jsx
This PR adds filtering for the job titles we receive from Algolia. This is done using the `Configure` component supplied by the `react-instantsearch-hooks-web` package.
[Documentation on `Configure`](https://www.algolia.com/doc/api-reference/widgets/configure/react-hooks/)
The filter had to be added to Algolia as well:
[APER-2405](https://2u-internal.atlassian.net/browse/APER-2405)
=> fix: adding configure component to filter jobs

src/skills-builder/skills-builder-modal/select-preferences/JobTitleSelect.jsx
Filtering was added for current job selection when we actually do not want to filter this list of jobs. We only need to filter the jobs that we intend to give recommendations for. This PR removes filtering for the `JobTitleSelect` component.
=> fix: remove filtering from current job select

src/skills-builder/skills-builder-modal/select-preferences/GoalSelect.jsx, src/skills-builder/skills-builder-modal/select-preferences/SelectPreferences.jsx
[APER-2337 -- Skills Builder's third prompt remains when currentGoal is reset to "Select a goal"](https://2u-internal.atlassian.net/browse/APER-2337) 
When filling out the Skills Builder form, the second and third parts of the form would appear once the learner selected a goal. A bug existed where the learner could answer all three parts of the form, "unselect" their goal by selecting "Select a goal", and only the second portion of the form would disappear -- not the third.
Prevent users from selecting "Select a goal" once a goal has been selected. They're now only able to switch among the acceptable goal options. For additional precaution, the third portion of the form will be hidden if the `currentGoal` is falsy.
=> fix: disable 'select a goal' from goal dropdown when a goal has been selected

src/skills-builder/skills-builder-modal/view-results/RecommendationCard.jsx
There was a typo in the attributes for the `RecommendationCard` component causing there to be no fallback image. This was making the course cards look awkward while waiting for the images to load.
=> fix: fallback src typo for course cards

src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/constants.js
this is a backport of https://github.com/openedx/frontend-app-profile/pull/667
When a user selects "Other Education" and clicks save - an error occurs.
It's caused by the wrong API call payload value `'o'` Fix: use the `'other'` payload value instead (the valid one).
=> fix: error when trying to save 'other education'

README.rst, catalog-info.yaml
These updates and additions meet the [Maintainership Pilot Phase 1 requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3578691585/Pilot+Phase+1) by providing a `catalog-info.yaml` file ([source](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html)) and updating the README to match [the template provided](https://github.com/openedx/frontend-template-application/blob/master/README-template-frontend-app.rst).
=> build: add catalog-info yaml and update README

package-lock.json, package.json, src/pacts/frontend-app-profile-edx-platform.json, src/profile/data/pact-profile.test.js
This PR creates consumer contracts between the Profile MFE and the LMS that will help define expectations between each service. These expectations will be coordinated through the Pact stub server in a Docker container. The next steps include implementing provider tests and verifying requests & responses in the User API repository listed [here](https://github.com/openedx/edx-platform/tree/96f13978720d3fc8760aa71e435dd7dad2782dcf/openedx/core/djangoapps/user_api). Ultimately, this stub server will replicate the entire LMS architecture in local development, increasing efficiency and improving developer experience as a whole.
I chose two basic Account API mock responses to stub out for the contract: A HTTP 200 response and a HTTP 404 Response. The contract's expected output is a `.json` file …
=> feat: Pact Consumer Contract Testing on LMS Account API

src/index.jsx
Added the missing 'ID' parameter for the main section. When we want to use keyboard navigation through the page, the first anchor we encounter on the account page is 'Skip to main content,' which allows us to skip the header and move to the content area. However, this anchor is linked to the #main ID, which is missing in the main section.
Before fix:
https://github.com/openedx/frontend-app-profile/assets/19806032/1bb407ae-51e0-4cc9-bbff-5aa30c56fe0c
After:
https://github.com/openedx/frontend-app-profile/assets/19806032/f3a4d83e-6aeb-426e-beda-5b0702f9b77d
=> fix: Add ID attribute to the main content

src/profile/ProfilePage.jsx, src/profile/ProfilePage.test.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/sagas.js, src/profile/data/selectors.js
- Fixed the display of fields in a user's profile when viewing it from our own account to another user's profile that was just created (by default, the fields Full name, Location, and Certificates (if any) are displayed).
- Fixed the display of empty fields in a user's profile when viewing it from our own account to another user's profile that was just created. Fields that are not filled in will not be displayed (previously, if a field was not filled in, the field name was displayed, but not the value).
- Fixed the behavior of forms for a newly created user. Previously, if you changed the value of one field to Just me for the first time, the values of other fields were also reset to Just me. Now, only the value of the edited field is changed.
=> feat: Fields visibility and visibility forms (palm.master)

src/profile/ProfilePage.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/forms/__snapshots__/SocialLinks.test.jsx.snap, src/profile/forms/elements/Visibility.jsx
This pull request contains minor fixes that occur when the user has a very long name and there are long choices in form elements.
In these cases, we have the text or element coming out of the sizes of the containers reserved for their display.
|  text overloading with an extremely long username |  incorrect left padding with a long username on mobile |  text overloading with a long option in form select |
|---|---|---|
| ![image](https://github.com/openedx/frontend-app-profile/assets/17108583/e2cdbee9-3720-4d0b-8af8-c8df8db81436)  |   ![image](https://github.com/openedx/frontend-app-profile/assets/17108583/9c03d648-4d40-453b-86c8-69ddb9b8f5fc) | ![image](https://github.com/openedx/frontend-app-profile/assets/17108583/b42b16f8-4a37-4f96-82ab-5ca7942e7101)
| with a long username with …
=> fix: trim long text in form controls and username block

src/profile/ProfilePluginPage.jsx
Context:
The Profile plugin component has a `view public profile` hyperlink, then when clicked would redirect the page _inside the plugin_ rather than the parent frame (AKA Host MFE).
This PR fixes that bug by adding `target=_parent` to the Hyperlink tag.
=> fix: "view public profile" link sends parent frame to URL

package-lock.json, package.json
[APER-2889]
The codecov package is no longer supported and we have moved to using a GitHub action for uploading coverage data. The NPM package can be removed from our requirements.
=> chore: remove unused codecov package from package.json

src/profile/ProfilePluginPage.jsx
This adds `overflow: hidden;` to the wrapper for the Plugin to hide scrollbars that will flicker when resizing.
=> fix: remove scrollbars

src/profile/ProfilePage.jsx, src/profile/ProfilePage.test.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/sagas.js, src/profile/data/selectors.js
- Fixed the display of fields in a user's profile when viewing it from our own account to another user's profile that was just created (by default, the fields Full name, Location, and Certificates (if any) are displayed).
- Fixed the display of empty fields in a user's profile when viewing it from our own account to another user's profile that was just created. Fields that are not filled in will not be displayed (previously, if a field was not filled in, the field name was displayed, but not the value).
- Fixed the behavior of forms for a newly created user. Previously, if you changed the value of one field to Just me for the first time, the values of other fields were also reset to Just me. Now, only the value of the edited field is changed.
=> feat: Fields visibility and visibility forms

src/profile/Banner.jsx, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/forms/Certificates.jsx
- Fixed displaying banner on mobile view
- Fixed displaying list of certificates on mobile view
=> feat: Fixed displaying banner and certificates on mobile view

package-lock.json, package.json
This is a partial revert for bd4b79baa0fb2a82b713a807f4a67bdbd42f93a9 which broke Tutor MFE.
- Tutor MFE issue: https://github.com/overhangio/tutor-mfe/pull/184#issuecomment-1966857727
I understand that the package is still `@edx` but until we set up the `@openedx` version, the current version must be used.
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
=> fix: get `@edx/openedx-atlas` back to fix Tutor MFE | FC-0012

package.json
This reverts commit a3611b026c6933bfcd91ea102e79fa298a6c8f75. This version of `testing-library/react` doesn't play well with our current version of React.
We shouldn't upgrade this library until we're running a newer version of React in this MFE.
=> revert: "chore(deps): update dependency @testing-library/react to v14"

package-lock.json, package.json
Upgrade to Paragon v22. The breaking changes are for components that are not used by this MFE (see [release notes](https://github.com/openedx/paragon/releases/tag/v22.0.0))
=> chore(deps): upgrade to paragon v22

src/profile/AgeMessage.jsx
Before this, the "Your profile cannot be shared." sentence was hardcoded and not translated.
@openedx/2u-aperture kindly have a look.
Close #1040
=> fix: make raw string a formatted message

.github/CODEOWNERS, .github/pull_request_template.md, README.rst, catalog-info.yaml
[INF-1551](https://2u-internal.atlassian.net/browse/INF-1551)
**Description**
As part of the maintainer ship program, we updated the catalog file of the Profile MFE to confirm that Edx-Infinity team will be maintaining the repo. 
The file needs to be updated according to [OEP-55: Project Maintainers — Open edX Proposals 1.0 documentation](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html#documenting-maintainers)
=> docs: updated catalog-info file for profile MFE

src/profile/ProfilePage.test.jsx, src/profile/__mocks__/savingEditedBio.mockStore.js, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/reducers.js, src/profile/data/selectors.js, src/profile/forms/Country.jsx
[INF-1567](https://2u-internal.atlassian.net/browse/INF-1567)
- Countries in the `disabledCountries` list will no longer be visible to users in the profile settings of other countries, and users will not be able to switch to disabled countries. 
- User with a disabled country selected can change their country to another one. After switching, they cannot select the disabled country again.
- Implemented frontend validation to verify the country against the disabled countries list to prevent invalid country submissions.
For Example, if Russia is on the disabled countries list.
> Other Country Users will not see Russia in the country list as an 
------------------------------------------------------------------------------------------------------------------------
> Russian user will see …
=> feat: added country disabling feature

.github/workflows/ci.yml, package-lock.json, package.json
Rebase with 2u-main after updating to reselect 5.1.1
=> Rebase with 2u-main

src/profile-v2/CertificateCard.jsx, src/profile-v2/Certificates.jsx, src/profile-v2/ProfilePage.jsx, src/profile-v2/UsernameDescription.jsx, src/profile-v2/__snapshots__/ProfilePage.test.jsx.snap, src/profile-v2/data/hooks.js, src/profile-v2/index.scss
[](url)Ticket: [INF-1708](https://2u-internal.atlassian.net/browse/INF-1708)
Fixed responsiveness issues on mobile and tablet views.
=> fix: fixed responsiveness issues on mobile view

src/profile/ProfilePage.jsx, src/profile/ProfilePage.test.jsx, src/profile/__mocks__/invalidUser.mockStore.js, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/reducers.js, src/profile/data/sagas.js, src/routes/AppRoutes.jsx
[INF-1594](https://2u-internal.atlassian.net/browse/INF-1594)
I resolved an issue that occurred when navigating to the learner profile of a non-existent user. Previously, the user's page would display a perpetual "loading" spinner, but it now correctly displays the content of the "Not Found" page.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
|-------|-----|
**Before**
**After**
=> feat: fixed reloading issue

src/profile/ProfilePage.jsx, src/profile/ProfilePage.test.jsx, src/profile/__mocks__/invalidUser.mockStore.js, src/profile/__snapshots__/ProfilePage.test.jsx.snap, src/profile/data/reducers.js, src/profile/data/sagas.js, src/routes/AppRoutes.jsx
[INF-1594](https://2u-internal.atlassian.net/browse/INF-1594)
I resolved an issue that occurred when navigating to the learner profile of a non-existent user. Previously, the user's page would display a perpetual "loading" spinner, but it now correctly displays the content of the "Not Found" page.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
**Before**
**After**
=> feat: fixed loading issue for wrong username

src/pacts/frontend-app-profile-edx-platform.json, src/profile-v2/ProfilePage.jsx, src/profile-v2/forms/Name.jsx, src/profile-v2/forms/Name.messages.jsx
Ticket: [INF-1890](https://2u-internal.atlassian.net/browse/INF-1890)
We added edit functionality for the full name field while making the Profile editable. While testing on stage, we observed that some users require ID Verification to change their full name. The flow for ID verification only exists in Accounts MFE. 
Hence, we are removing the edit functionality of the full name field and providing a redirect link to edit it on the Accounts page instead.
=> feat: made fullname uneditable and added redirect link
